trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'any cpu'
  PathToBuildProjects: '**/*.csproj'
  PathToNugetProjects: '**/*.csproj' 

steps:
    #task: Use .NET Core sdk 5.x
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 5.x' 
  inputs:
    version: 5.x

    #task: Restore
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: $(PathToBuildProjects)

    #task: Build
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: $(PathToBuildProjects)
    arguments: '--configuration $(BuildConfiguration)'

    #task: Install Nuget tool otherwise following task with powershell command nuget push will fail
- task: NuGetToolInstaller@1
  displayName: 'Install Nuget Tool'
  inputs:
    versionSpec: '5.7.0'
    checkLatest: true

    #task: Pack
- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: $(PathToNugetProjects)

    #task: NuGet push nuget.org
    #link: https://stackoverflow.com/questions/52920786/publish-nuget-package-using-azure-devops
- task: PowerShell@2
  displayName: 'NuGet push nuget.org'
  inputs:
    targetType: 'inline'
    script: 'nuget push $(Build.ArtifactStagingDirectory)\*.nupkg -ApiKey $env:Api_Key -Source https://api.nuget.org/v3/index.json -SkipDuplicate'
  env:
    Api_Key: $(FeriApiKey)

    #task: Publish Artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
